### ISSUE TITLE
How to run the nose tests?

### ISSUE THREAD

**Issue by psafont** [common-workflow-language/cwl-tes#18]
As an effort to allow testing using tox, independently of travis; I've been trying to run the tests following .travis.yml but I'm hitting a strange error about a missing file 

This means:
* Run `git submodule update --init --recursive`
* Placed funnel in `$PATH`
* Installed (test) dependencies

I'm receiving this output:

```
$ python -m nose ./tests
E
======================================================================
ERROR: test_conformance (tests.test_conformance.TestConformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/psafont/dev/ga4gh/cwl-tes/tests/test_conformance.py", line 36, in test_conformance
    bufsize=1
  File "/home/psafont/dev/ga4gh/cwl-tes/tests/funnel_test_util.py", line 34, in popen
    return subprocess.Popen(*args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-------------------- >> begin captured stdout << ---------------------
RUNNNING: cwltest --test /home/psafont/dev/ga4gh/cwl-tes/tests/schemas/v1.0/conformance_test_v1.0.yaml --basedir /home/psafont/dev/ga4gh/cwl-tes/tests/test_tmp/conformance_test_v1.0_jIwQ0T --tool /home/psafont/dev/ga4gh/cwl-tes/cwl-tes -j 20 -- --tes=http://localhost:8000

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Running funnel server run --config /home/psafont/dev/ga4gh/cwl-tes/tests/test_tmp/conformance_test_v1.0_jIwQ0T/tmpFgqlI4
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 1.017s

FAILED (errors=1)
```

None of the files mentioned in the log are missing, so I don't really know what's up.

**Comment by adamstruck** [comment]
Great! Let me know if you have any issues.  It's been awhile since I updated things.  The open PR uses a much newer version of cwltool, but tests fail due to a bug in the parallel mode of cwltool.
